name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-check:
    name: runner / typos (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / typos (github-pr-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning
          workdir: ./testdata/subdir/

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / typos (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: ./
        continue-on-error: true
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          filter_mode: file
          fail_level: any
      - name: check the exit code
        if: ${{ !success() }}
        run: echo 'The previous step should fail' && exit 1
